name: 🎯 OKR
description: File a goal that needs to be achieved.
body: 
- type: textarea
  attributes: 
    label: Objective
    description: Write an inspirational and activating description of the goal state.
  validations:
    required: true
- type: textarea
  attributes:
    label: Key Results
    description: Concretize the objective by listing the concrete benchmarks for achieving the goal.
  validations: 
    required: true
- type: textarea
  attributes:
    label: OKR metadata
    description: You can fill in the optional data for OKR (score, confidence level, supervisor).
